name: Build LaTeX document

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_latex:
    name: Compile LaTeX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
          extra_system_packages: "font-liberation"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: resume.pdf
